apiVersion: v1
kind: Template
metadata:
  name: kafkanetes-debug
  annotations:
    description: Kafkanetes debugging pod
    tags: messaging,kafka,zookeeper

parameters:
- name: OBJECT_NAME_PREFIX
  description: Name prefix for each object created
  required: true
  value: kafkanetes-debug
- name: IMAGESTREAM
  description: Kafkanetes imagestream name
  required: true
  value: kafkanetes

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${OBJECT_NAME_PREFIX}
    template:
      metadata:
        labels:
          deploymentconfig: ${OBJECT_NAME_PREFIX}
      spec:
        containers:
        - name: kafkanetes
          image: ${IMAGESTREAM}
          command:
          - python
          args:
          - -c
          - import signal; signal.pause()
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: false
        containerNames:
        - kafkanetes
        from:
          kind: ImageStream
          name: ${IMAGESTREAM}
