apiVersion: v1
kind: Template
metadata:
  name: kafkanetes-deploy-zk-1
  annotations:
    description: 1-pod ZooKeeper
    tags: messaging,zookeeper

parameters:
- name: VOLUME_CAPACITY
  description: Persistent volume capacity per pod, e.g. 512Mi, 2Gi
  required: true
  value: 512Mi
- name: OBJECT_NAME_PREFIX
  description: Name prefix for each object created
  required: true
  value: kafkanetes-zk
- name: IMAGESTREAM
  description: Kafkanetes imagestream name
  required: true
  value: kafkanetes

objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${OBJECT_NAME_PREFIX}
    template:
      metadata:
        labels:
          deploymentconfig: ${OBJECT_NAME_PREFIX}
      spec:
        containers:
        - name: kafkanetes
          image: ${IMAGESTREAM}
          command:
          - bin/zookeeper-server-start.sh
          args:
          - config/zookeeper.properties
          volumeMounts:
          - mountPath: /tmp/zookeeper
            name: zookeeper
          ports:
          - containerPort: 2181
        volumes:
        - name: zookeeper
          persistentVolumeClaim:
            claimName: ${OBJECT_NAME_PREFIX}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: false
        containerNames:
        - kafkanetes
        from:
          kind: ImageStream
          name: ${IMAGESTREAM}

- apiVersion: v1
  kind: Service
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    ports:
    - port: 2181
    selector:
      deploymentconfig: ${OBJECT_NAME_PREFIX}
